name: tests

defaults:
  run:
    shell: bash

on:
  pull_request:
    branches: [ "master" ]

jobs:
  run_tests:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-root --without dev
      - name: Test with pytest
        run: |
          source C:\Users\runneradmin\AppData\Local\pypoetry\Cache\virtualenvs
          pytest tests/
